* <h3>Consider the below code to answer further questions:

In [5]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

<h3>Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables

Yes, there is a difference in the data types of the list_ variable and the array_list variable.

The list_ variable is a Python list object, while the array_list variable is a NumPy array object. The elements of list_ are of type string, while the elements of array_list are of type numpy.str_ .

In [12]:
print("the type of list is: ", type(list_))
print("the type of array_list is: ", type(array_list))

the type of list is:  <class 'list'>
the type of array_list is:  <class 'numpy.ndarray'>


<h3>Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list

In [28]:
print("Type of elements in list_  is:\n")    
for i in list_:
    print(type(i))
print("\nType of elements in array_list is:\n")    
for j in array_list:
    print(type(j))

Type of elements in list_  is:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Type of elements in array_list is:

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


<h3>Q3. Considering the following changes in the variable, array_list:

In [33]:
array_list = np.array(object = list_, dtype = int)

<h3>Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Yes,there will difference in the data type of the array_list only , list_ valriable will remain same, because we created the `array_list` by assigning array_list = np.array(object = list_, dtype = int), here we specified the data type as `int` , meaning that the elements of array_list will be of int type 

In [34]:
print("Type of elements in list_  is:\n")    
for i in list_:
    print(type(i))
print("\nType of elements in array_list is:\n")    
for j in array_list:
    print(type(j))

Type of elements in list_  is:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Type of elements in array_list is:

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


* <h3>Consider the below code to answer further questions:

In [35]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [36]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

<h3>Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [39]:
print("The shape of array is : ",num_array.shape)

the shape of array is :  (2, 3)


In [41]:
print("The size of array is : ",num_array.size)

The size of array is :  6


<h3>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function

In [45]:
arr = np.zeros((3,3))

In [46]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
print('shape: ',arr.shape)
print('size: ',arr.size)

shape:  (3, 3)
size:  9


<h3>Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [54]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])